package io.seanbailey.sqladapter;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Tests the SQL generated by various different chain functions.
 */
public class QueryTests {

  @Test
  public void testAll() {
    String sql = Model.all(TestModel.class).toString();
    assertEquals(sql, "SELECT * FROM");
  }

  @Test
  public void testAllCount() {
    String sql = Model.all(TestModel.class).count().toString();
    assertEquals(sql, "SELECT COUNT(*) FROM");
  }

  @Test
  public void testAllExists() {
    String sql = Model.all(TestModel.class).exists().toString();
    assertEquals(sql, "SELECT COUNT(*) FROM");
  }
}
